### ISSUE TITLE
Poor reception with RFM69HWC

### ISSUE THREAD

**Issue by Eli-S-Bridge** [iwanders/plainRFM69#16]
I'm running example scripts with an RFM69HWC. The code works but I am getting only intermittant reception with communication between two radios running on modified M0 arduinos. When I use the radiohead library reception is perfect (so the hardware is OK). But I would prefer to use plainRFM69 so I can have control over interrupts. I just can't figure out what I need to do to get the transmission to work properly. I've got a high power version of the radio, and I've tried several variations on rfm.setTxPower(14, true), but there's no effect on reception. I will note that touching one of the antennas improves reception, which imples hardware issues. But again, everything works with the example scripts in radiohead. I'm just wondering if there's some incompatibility with RFM69HWC that I'm unaware of.

**Comment by iwanders** [comment]
Which frequency of chip? I wonder if you run into https://github.com/iwanders/plainRFM69/pull/13  I never got word back from testing of that, but an overflow in the frequency could affect the results. Can you try that branch?

**Comment by Eli-S-Bridge** [comment]
I'm using 434mHz modules, so a 32bit overflow is probably not the issue.

**Comment by Eli-S-Bridge** [comment]
By the way, thanks for responding....
I pulled out all the RFM69 registers from a plainRFM69 script and from radiohead (see below). There might be a clue among the differing registers. For instance, I was surprised to see the carrier frequency bytes (RegFrf...) were different. I'm not sure I have time to parse all of these registers out, but I suspect the difference in performance is explained in there somewhere.
```
PlainRFM69     |   Radiohead       |  register description
reg no: value     reg no: value.       reg no, name, defaults, description

0x0: 0x0   | 0x0: 0x0   | 0x00 RegFifo 0x00 FIFO read/write   access
0x1: 0x10  | 0x1: 0x4   | 0x01 RegOpMode 0x04 Operating modes of the transceiver
0x2: 0x0   | 0x2: 0x1   | 0x02 RegDataModul 0x00 Data operation mode and Modulation   settings 
0x3: 0x1A  | 0x3: 0x0   | 0x03 RegBitrateMsb 0x1A Bit Rate setting, Most Significant   Bits
0x4: 0xB   | 0x4: 0x80  | 0x04 RegBitrateLsb 0x0B Bit Rate setting, Least Significant   Bits
0x5: 0x0   | 0x5: 0x10  | 0x05 RegFdevMsb 0x00 Frequency Deviation setting, Most   Significant Bits
0x6: 0x52  | 0x6: 0x0   | 0x06 RegFdevLsb 0x52 Frequency Deviation setting, Least   Significant Bits
0x7: 0x6C  | 0x7: 0x6C  | 0x07 RegFrfMsb 0xE4 RF Carrier Frequency, Most Significant   Bits
0x8: 0x90  | 0x8: 0x80  | 0x08 RegFrfMid 0xC0 RF Carrier Frequency, Intermediate Bits
0x9: 0x2   | 0x9: 0x0   | 0x09 RegFrfLsb 0x00 RF Carrier Frequency, Least Significant   Bits
0xA: 0x41  | 0xA: 0x41  | 0x0A RegOsc1 0x41 RC Oscillators Settings
0xB: 0x40  | 0xB: 0x40  | 0x0B RegAfcCtrl 0x00 AFC control in low modulation index   situations
0xC: 0x2   | 0xC: 0x2   | 0x0C Reserved0C 0x02 -
0xD: 0x92  | 0xD: 0x92  | 0x0D RegListen1 0x92 Listen Mode settings
0xE: 0xF5  | 0xE: 0xF5  | 0x0E RegListen2 0xF5 Listen Mode Idle duration
0xF: 0x20  | 0xF: 0x20  | 0x0F RegListen3 0x20 Listen Mode Rx duration
0x10: 0x24 | 0x10: 0x24 | 0x10 RegVersion 0x24
0x11: 0x9F | 0x11: 0x7F | 0x11 RegPaLevel 0x9F PA selection and Output Power control
0x12: 0x9  | 0x12: 0x9  | 0x12 RegPaRamp 0x09 Control of the PA ramp time in FSK mode
0x13: 0x1A | 0x13: 0x1A | 0x13 RegOcp 0x1A Over Current Protection control
0x14: 0x40 | 0x14: 0x40 | 0x14 Reserved14 0x40 -
0x15: 0xB0 | 0x15: 0xB0 | 0x15 Reserved15 0xB0 -
0x16: 0x7B | 0x16: 0x7B | 0x16 Reserved16 0x7B -
0x17: 0x9B | 0x17: 0x9B | 0x17 Reserved17 0x9B -
0x18: 0x88 | 0x18: 0x8  | 0x18 RegLna 0x08 0x88 LNA settings
0x19: 0x55 | 0x19: 0xE0 | 0x19 RegRxBw 0x86 0x55 Channel Filter BW Control
0x1A: 0x8B | 0x1A: 0xE0 | 0x1A RegAfcBw 0x8A 0x8B Channel Filter BW control during the   AFC routine
0x1B: 0x40 | 0x1B: 0x40 | 0x1B RegOokPeak 0x40 OOK demodulator selection and control in   peak mode
0x1C: 0x80 | 0x1C: 0x80 | 0x1C RegOokAvg 0x80 Average threshold control of the OOK   demodulator
0x1D: 0x6  | 0x1D: 0x6  | 0x1D RegOokFix 0x06 Fixed threshold control of the OOK   demodulator
0x1E: 0x10 | 0x1E: 0x10 | 0x1E RegAfcFei 0x10 AFC and FEI control and status
0x1F: 0x0  | 0x1F: 0x0  | 0x1F RegAfcMsb 0x00 MSB of the frequency correction of the AFC
0x20: 0x0  | 0x20: 0x0  | 0x20 RegAfcLsb 0x00 LSB of the frequency correction of the AFC
0x21: 0x0  | 0x21: 0x0  | 0x21 RegFeiMsb 0x00 MSB of the calculated frequency error
0x22: 0x0  | 0x22: 0x0  | 0x22 RegFeiLsb 0x00 LSB of the calculated frequency error
0x23: 0x0  | 0x23: 0x2  | 0x23 RegRssiConfig 0x02 RSSI-related settings
0x24: 0xBE | 0x24: 0xFF | 0x24 RegRssiValue 0xFF RSSI value in dBm
0x25: 0x0  | 0x25: 0x0  | 0x25 RegDioMapping1 0x00 Mapping of pins DIO0 to DIO3
0x26: 0x5  | 0x26: 0x5  | 0x26 RegDioMapping2 0x05 0x07 Mapping of pins DIO4 and DIO5,   ClkOut frequency
0x27: 0xD8 | 0x27: 0x80 | 0x27 RegIrqFlags1 0x80 Status register: PLL Lock state,   Timeout, RSSI > Threshold...
0x28: 0x0  | 0x28: 0x0  | 0x28 RegIrqFlags2 0x00 Status register: FIFO handling flags...
0x29: 0xE4 | 0x29: 0xFF | 0x29 RegRssiThresh 0xFF 0xE4 RSSI Threshold control
0x2A: 0x0  | 0x2A: 0x0  | 0x2A RegRxTimeout1 0x00 Timeout duration between Rx request   and RSSI detection
0x2B: 0x0  | 0x2B: 0x0  | 0x2B RegRxTimeout2 0x00 Timeout duration between RSSI   detection and PayloadReady
0x2C: 0x0  | 0x2C: 0x0  | 0x2C RegPreambleMsb 0x00 Preamble length, MSB
0x2D: 0x3  | 0x2D: 0x4  | 0x2D RegPreambleLsb 0x03 Preamble length, LSB
0x2E: 0x98 | 0x2E: 0x88 | 0x2E RegSyncConfig 0x98 Sync Word Recognition control
0x2F: 0x1  | 0x2F: 0x2D | 0x2F-0x36 RegSyncValue1-8 0x00 0x01 Sync Word bytes, 1 through   8
0x30: 0x1  | 0x30: 0xD4 |  
0x31: 0x1  | 0x31: 0x0  |  
0x32: 0x1  | 0x32: 0x0  |  
0x33: 0x0  | 0x33: 0x0  |  
0x34: 0x0  | 0x34: 0x0  |  
0x35: 0x0  | 0x35: 0x0  |  
0x36: 0x0  | 0x36: 0x0  |  
0x37: 0x50 | 0x37: 0xD0 | 0x37 RegPacketConfig1 0x10 Packet mode settings
0x38: 0x4  | 0x38: 0x40 | 0x38 RegPayloadLength 0x40 Payload length setting
0x39: 0x0  | 0x39: 0x0  | 0x39 RegNodeAdrs 0x00 Node address
0x3A: 0x0  | 0x3A: 0x0  | 0x3A RegBroadcastAdrs 0x00 Broadcast address
0x3B: 0x85 | 0x3B: 0x0  | 0x3B RegAutoModes 0x00 Auto modes settings
0x3C: 0x1  | 0x3C: 0x8F | 0x3C RegFifoThresh 0x0F 0x8F Fifo threshold, Tx start   condition
0x3D: 0x0  | 0x3D: 0x2  | 0x3D RegPacketConfig2 0x02 Packet mode settings
```

Edit; put the table in triple backticks for monospace and added some spaces for alignment.

**Comment by iwanders** [comment]
Thanks for providing comparison!

>  I'm not sure I have time to parse all of these registers out

I think the difference (ignoring some register that I think don't matter) boils down to:
```
RegFrf
  plainRFM:  0x6c9002 -> 0x6c9002 * 61 = 433999994 Hz
  radiohead: 0x6c8000 -> 0x6c8000 * 61 = 433750016 Hz
RegFdev:
  plainRFM:  0x0052 -> 0x0052 * 61 = 5002  Hz
  radiohead: 0x1000 -> 0x1000 * 61 = 249856  Hz
RegPacketConfig1
  plainRFM:  0x50=0b01010000 -> fixed length, whitening, crc
  radiohead: 0xD0=0b11010000 -> variable length, whitening, crc
RegSyncConfig
  plainRFM:  0x98=0b10011000 -> SyncSize:3 + 1 = 4,SyncOn
  radiohead: 0x88=0b10001000 -> SyncSize:1 + 1 = 2,SyncOn
RegSyncValue{0..8}
  PlainRFM: [0x1, 0x1, 0x1, 0x1] = [0b00000001, 0b00000001, 0b00000001, 0b00000001]
  RadioHead: [0x2D, 0xD4] = [0b00101101, 0b11010100]
RegDataModul:
  PlainRFM: no shaping
  Radiohead: 01, Gaussian filter BT=1.0
RegBitrate{Msb,Lsb}:
  plainRFM:  0x1a0b = 6667 -> 32e6(FXO_SC) / 6667 = 4799.7600119994 bit/s
  radiohead: 0x0080 =  128 -> 32e6(FXO_SC) / 128 = 250000.0 bit/s
RegPaLevel:
  plainRFM:  0x9F = 0b10011111 -> Pa0: on, pa1: off, pa2: off
  raiodhead: 0x7F = 0b01111111 -> Pa0: off, pa1: on, pa2: on
RegRssiThresh:
  plainRFM: 0xe4 -> -114 dbm
  radiohead: 0xff -> -128 dbm
RegRxBw:
  plainRFM:  0x55
  radiohead: 0xe0
RegAfcBw:
  plainRFM:  0x8b
  radiohead: 0x1a
RegPreamble :
  plainrfm: Preamblesize: 3 bytes
  radiohead: Preamblesize:  4 bytes
RegPayloadLength:
  plainrfm: fixed 4 bytes
  radiohead: variable
RegPacketConfig2:
  plainrfm: nothing
  radiohead: restart Rx after receipt.
RegFifoThresh:
  plainRFM: fifolevel, with 1
  radiohead; fifo not empty, with 0b1111
```



> For instance, I was surprised to see the carrier frequency bytes (RegFrf...) were different.

The difference isn't that large, just multiply the register with 61 to get the frequency in Hz; 433999994 for plainRFM, 433750016 for radiohead. You could use [setFrequency](https://github.com/iwanders/plainRFM69/blob/152a9a435acc24a2f5783991ee41bc271be5552a/plainRFM69.cpp#L98C18-L98C30)  with `433750016` to get the exact same as radiohead.

One thing that does stand out to me is the SyncValues; `RegSyncValue` in the above, for plainRFM this is set to `0x01`, but this data is not whitened (page 52 of the datasheet), so those may actually be bad values... I know that's set by [this section](https://github.com/iwanders/plainRFM69/blob/152a9a435acc24a2f5783991ee41bc271be5552a/plainRFM69.cpp#L23-L26) but it may be worth changing to what radiohead uses.

Another; `RegPaLevel`, see above comparison, switch that to be the same as Radioheads, I'm not sure if all chips support the power amplifier options used here.

In this comparison, the baudrates are vastly different, with 4.8kb/s vs 250kb/s, that means transmissions take a pretty significant different duration, if there's any (periodic) interference in the environment plainRFM would be much more affected by that, you could try running `setRecommended()` followed by `baud300000()`, that sets it up for 300kb/s, which may set things up more similar to radiohead. Maybe even try this first, depending on the environment this may make a world of difference.

When I developed this library years ago I only really tested with three radios and short ranges. That project (not on github) used the following in the initialization;
```cpp
    this->rfm->setRecommended(); // set recommended paramters in RFM69.

    this->rfm->setPacketType(true, true); // set the used packet type.
    this->rfm->setBufferSize(this->buffer_size);   // set the internal buffer size.
    this->rfm->setPacketLength(64); // set the packet length.
    this->rfm->setFrequency(this->frequency); // set the frequency.

    this->rfm->setNodeAddress(this->kernel->getPlatformAddress());
    this->rfm->setBroadcastAddress(PLATFORM_ADDRESS_BROADCAST);

    this->rfm->baud153600();
    this->rfm->setPreambleSize(10); 

    // tell the RFM to represent whether we are in automode on DIO 2.
    this->rfm->setDioMapping1(RFM69_PACKET_DIO_2_AUTOMODE);

    // set pinmode to input.
    pinMode(this->dio2_pin, INPUT);

    // Tell the SPI library we're going to use the SPI bus from an interrupt.
    SPI.usingInterrupt(this->dio2_pin);

    // hook our interrupt function to any edge.
    attachInterrupt(this->dio2_pin, interrupt_RFM, CHANGE);

    // start receiving.
    this->rfm->receive();
```

I only needed like 3 meters of range and for that it seemed to work well. But it's like 10 years ago, so I probably forgot countless weeks of frustration trying to get it to work reliably ;)

Hope this gives you some pointers on what you could try and what the differences are. Remember that `plainRFM` [subclasses](https://github.com/iwanders/plainRFM69/blob/152a9a435acc24a2f5783991ee41bc271be5552a/plainRFM69.h#L57) from [`bareRFM69`](https://github.com/iwanders/plainRFM69/blob/master/bareRFM69.h), so you can call any of those methods to directly modify registers.
